# Generated by Django 5.0.4 on 2024-05-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RenameField(
            model_name='coverletter',
            old_name='text',
            new_name='cover_letter',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='email',
            new_name='rec_email',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='place_of_work',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='may_be_contacted',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='role',
        ),
        migrations.AddField(
            model_name='experience',
            name='workplace',
            field=models.CharField(default='Elko', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='rec_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='rec_name',
            field=models.CharField(default='Johanson', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='rec_phone',
            field=models.CharField(default='6969420', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='rec_role',
            field=models.CharField(default='Meistari', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
