# Generated by Django 5.0.4 on 2024-05-17 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_application_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contact_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='application.contactinformation'),
        ),
    ]
