# Generated by Django 5.0.4 on 2024-05-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobHub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='CompanyImage',
            old_name='name',
            new_name='image',
        ),
    ]
