# Generated by Django 5.0.4 on 2024-05-15 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHub', '0003_job_location'),
        ('company', '0004_delete_companyimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyimage',
            name='Company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
