# Generated by Django 5.0.4 on 2024-05-15 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHub', '0004_companyimage_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyimage',
            name='Job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JobHub.job'),
        ),
    ]
