# Generated by Django 5.0.4 on 2024-05-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHub', '0005_alter_companyimage_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyimage',
            old_name='Company',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='companyimage',
            name='Job',
        ),
        migrations.AddField(
            model_name='job',
            name='job_requirements',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyimage',
            name='image',
            field=models.URLField(max_length=9999),
        ),
    ]
