# Generated by Django 5.0.4 on 2024-05-15 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHub', '0006_rename_company_companyimage_company_and_more'),
        ('company', '0005_remove_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyimage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='company.company'),
        ),
    ]
