# Generated by Django 5.0.4 on 2024-05-15 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHub', '0007_alter_companyimage_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=255)),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobHub.job')),
            ],
        ),
    ]
