# Generated by Django 5.0.4 on 2024-05-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHub', '0008_jobrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_requirements',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
