# Generated by Django 5.0.4 on 2024-05-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companyimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyImages',
        ),
    ]
