# Generated by Django 5.0.4 on 2024-05-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_delete_companyimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
    ]
