# Generated by Django 5.0.4 on 2024-05-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='link_to_page',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyStart_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
