# Generated by Django 5.0.4 on 2024-05-16 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="about",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
        migrations.AddField(
            model_name="profile",
            name="birthday",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
