# Generated by Django 5.0.4 on 2024-05-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_profile_birthday_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="",
                height_field="profile_picture_height",
                upload_to="",
                width_field="profile_picture_width",
            ),
        ),
    ]
